// Pidgin phrases database
const pidginPhrases = {
    dailyPhrases: [
        {
            pidgin: "Howzit, brah!",
            english: "How are you, friend!",
            usage: "A casual greeting used among friends in Hawaii"
        },
        {
            pidgin: "Eh, no make li'dat!",
            english: "Hey, don't do that!",
            usage: "Used to tell someone to stop doing something"
        },
        {
            pidgin: "We go grind!",
            english: "Let's eat!",
            usage: "Invitation to share a meal together"
        },
        {
            pidgin: "Da buggah stay broke",
            english: "That thing is broken",
            usage: "Describing something that doesn't work"
        },
        {
            pidgin: "Ho, da waves stay pumping!",
            english: "Wow, the waves are really good!",
            usage: "Expressing excitement about surf conditions"
        },
        {
            pidgin: "Try wait, yeah?",
            english: "Please wait a moment",
            usage: "Politely asking someone to be patient"
        },
        {
            pidgin: "No need beef",
            english: "There's no need to fight",
            usage: "Calming down a tense situation"
        }
    ],

    // Translation dictionary for common words and phrases
    translationDict: {
        // Common words
        "hello": "howzit",
        "hi": "howzit",
        "friend": "brah",
        "brother": "brah",
        "sister": "sistah",
        "food": "grinds",
        "eat": "grind",
        "eating": "grinding",
        "good": "good",
        "very good": "da kine good",
        "delicious": "broke da mouth",
        "a lot": "choke",
        "many": "choke",
        "plenty": "choke",
        "thing": "da kine",
        "things": "da kine stuff",
        "work": "hana",
        "after work": "pau hana",
        "done": "pau",
        "finished": "pau",
        "okay": "shoots",
        "alright": "shoots",
        "yes": "yeah",
        "no": "no",
        "cannot": "no can",
        "can't": "no can",
        "want": "like",
        "wants": "like",
        "don't": "no",
        "doesn't": "no",
        "is": "stay",
        "are": "stay",
        "was": "was",
        "were": "was",
        "the": "da",
        "that": "dat",
        "this": "dis",
        "what": "wat",
        "where": "wea",
        "when": "wen",
        "why": "why",
        "how": "how",
        "come": "come",
        "go": "go",
        "going": "going",
        "went": "wen go",
        "house": "hale",
        "home": "hale",
        "beach": "beach",
        "ocean": "ocean",
        "water": "wai",
        "mountain": "mauka",
        "toward the ocean": "makai",
        "car": "ride",
        "drive": "cruise",
        "fast": "fast",
        "slow": "slow",
        "big": "big",
        "small": "small",
        "little": "litto",
        "very": "real",
        "really": "real",
        "super": "choke",
        "awesome": "mean",
        "cool": "cool",
        "nice": "nice",
        "beautiful": "beautiful",
        "pretty": "pretty",
        "ugly": "hamajang",
        "broken": "broke",
        "messed up": "hamajang",
        "crazy": "lolo",
        "stupid": "lolo",
        "smart": "akamai",
        "clever": "akamai",
        "tired": "tired",
        "sleep": "moemoe",
        "sleeping": "moemoe",
        "wake up": "wake up",
        "tomorrow": "tomorrow",
        "yesterday": "yesterday",
        "today": "today",
        "later": "bumbye",
        "now": "now",
        "wait": "wait",
        "please wait": "try wait",
        "thank you": "tanks",
        "thanks": "tanks",
        "you're welcome": "no worries",
        "excuse me": "excuse",
        "sorry": "sorry",
        "please": "please",

        // Common phrases
        "how are you": "howzit",
        "what's up": "howzit",
        "see you later": "latahs",
        "take care": "malama",
        "let's go": "we go",
        "let's eat": "we go grind",
        "come here": "come",
        "go away": "hele on",
        "hurry up": "wiki wiki",
        "slow down": "slow down",
        "be quiet": "shh",
        "shut up": "shut up",
        "i don't know": "i no know",
        "i know": "i know",
        "do you understand": "you sabe",
        "i understand": "i sabe",
        "what did you say": "wat you said",
        "never mind": "no mind",
        "no problem": "no worries",
        "of course": "shoots",
        "for sure": "fo' real",
        "are you sure": "you sure or wat",
        "i'm hungry": "i stay hungry",
        "i'm tired": "i stay tired",
        "i'm good": "i stay good",
        "that's good": "dat's good",
        "that's not good": "dat's no good",
        "it's okay": "stay okay",
        "it's broken": "stay broke",
        "where are you going": "wea you going",
        "what are you doing": "wat you doing",
        "can you help me": "you can help me or wat",
        "i need help": "i need help",
        "come with me": "come wit me",
        "wait for me": "wait fo' me",
        "look at that": "look dat",
        "over there": "ova dea",
        "right here": "right hea",
        "long time no see": "long time no see",
        "what's wrong": "wat's wrong",
        "everything is fine": "everything stay good",
        "take it easy": "take it easy",
        "good job": "good job",
        "well done": "good job",
        "be careful": "watch out",
        "watch out": "watch out"
    },

    // Greetings and common expressions
    greetings: [
        { pidgin: "Howzit", english: "Hello/How are you", context: "Universal greeting" },
        { pidgin: "Shoots", english: "Okay/Sounds good", context: "Agreement" },
        { pidgin: "Rajah dat", english: "Roger that/Got it", context: "Understanding" },
        { pidgin: "Latahs", english: "See you later", context: "Saying goodbye" },
        { pidgin: "Tanks ah", english: "Thank you", context: "Gratitude" },
        { pidgin: "No worries", english: "You're welcome", context: "Response to thanks" }
    ]
};

// Function to get daily phrase (changes daily)
function getDailyPhrase() {
    const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0)) / 86400000);
    const index = dayOfYear % pidginPhrases.dailyPhrases.length;
    return pidginPhrases.dailyPhrases[index];
}