-- Create translation cache table
CREATE TABLE IF NOT EXISTS public.translation_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_text TEXT NOT NULL,
    translated_text TEXT NOT NULL,
    direction TEXT NOT NULL, -- 'eng-to-pidgin' or 'pidgin-to-eng'
    voice_id TEXT, -- For TTS caching
    audio_filename TEXT, -- Path in storage bucket
    md5_hash TEXT NOT NULL, -- For fast lookups
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_accessed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_translation_cache_hash ON public.translation_cache(md5_hash);

-- Constraint to prevent duplicate translations for same text/direction/voice
CREATE UNIQUE INDEX IF NOT EXISTS idx_translation_cache_unique_entry 
ON public.translation_cache(md5_hash, direction, COALESCE(voice_id, 'none'));

-- RLS Policies
ALTER TABLE public.translation_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Access"
ON public.translation_cache FOR SELECT
USING (true);

-- Admin can do everything
CREATE POLICY "Admin All Access"
ON public.translation_cache FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
